# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('firstname', models.CharField(max_length=200)),
                ('fieldid', models.IntegerField()),
                ('data', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('firstname', models.CharField(max_length=200)),
                ('Class', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('coursename', models.CharField(max_length=100)),
                ('gradebookitem', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('substring', models.CharField(blank=True, max_length=1000)),
                ('raw_grade', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
