# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='substring',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
