# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20180309_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='section',
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='Class',
            field=models.CharField(max_length=50),
        ),
    ]
