# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20180310_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='stclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A1',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A2',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A3',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A4',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A5',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A6',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A7',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='A8',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B1',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B2',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B3',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B4',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B5',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B6',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B7',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='B8',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C1',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C2',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C3',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C4',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C5',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C6',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C7',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='C8',
        ),
        migrations.AddField(
            model_name='studentid',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentid',
            name='sclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card.stclass'),
        ),
    ]
